version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - '3001:3001'
    volumes:
      - ./backend:/app
      - /app/node_modules
    env_file:
      - ./backend/.env
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - '3000:80'
    # volumes:
    #   - ./frontend:/usr/share/nginx/html
    depends_on:
      - backend

  db:
    image: mysql:8.0
    container_name: mysql_senhas
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: senha
    ports:
      - "3307:3306"
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
